CONFIG_CPP=y
CONFIG_STD_CPP23=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_PICOLIBC=y
CONFIG_CPP_RTTI=n
CONFIG_CPP_EXCEPTIONS=n

CONFIG_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n

CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_COMPILER_OPT="-O3"
CONFIG_LTO=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y
